[build-system]
requires = ["setuptools >= 69"]
build-backend = "setuptools.build_meta"

[project]
name = "paddlex-hps-server"
version = "0.2.2"
# `paddlex` is not included here
dependencies = [
    "colorlog >= 6.9",
    "pydantic >= 2",
]

[tool.isort]
profile = "black"
src_paths = ["src"]
